Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/AbcSize:
  Max: 20
